version: '3'
services:
  database:
    container_name: mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jqyden
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: msa-default
