version: '3'
services:
  database:
    container_name: mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jayden
      MYSQL_PASSWORD: password-prod
      MYSQL_DATABASE: msa-prod

